import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Navbar } from "reactstrap";
import { ContactUs } from "~/components/ContactUs";
import { Education } from "~/containers/Education";
import { Proficiency } from "~/containers/Proficiency";
import Projects from "~/containers/Projects";
import { Feedbacks } from "~/containers/feedbacks";
import { Greetings } from "~/containers/greetings";
import Skills from "~/containers/skills";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ahmad Sofanati</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Greetings />
      <Skills />
      <Proficiency />
      <Education />
      <Feedbacks />
      <Projects />
      <ContactUs />
    </>
  );
}
